# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2U5MmI2MDA3MzE4ZTMzOWFjYWRkOTU0OWNjODc0NWIyZTI1MzRhZGRlNmVkODYzZDZjN2MyMWI5ZjRmOGZkMTA5ODIyNDMyMjJlZmU1ZjAzNTdmMzhhOTY1Njk5Mjk3MWZkYWFlZmZiM2NkYThjOTJlZDcxYzkzYmNkNTI1ZTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
